export const DEMO_PROFILE_PREAMBLE = [
  'Om dig:',
  '• Du hedder Frederik Lund og er partner i konsulenthuset Lundgreen & Partner.',
  '• Du leder et team på fem og foretrækker korte mails uden lange hilsner.',
  '• Du lægger helst møder før kl. 15 og løber tirsdag og torsdag kl. 6.30.',
  '',
  'Relationer:',
  '• Maria Bergmann – managing partner og din nærmeste sparringspartner.',
  '• Sofia Wang – produktkonsulent på dit team.',
  '• Jonas Krogh – seniorkonsulent og nær ven.',
  '• Louise Berg – praktikant til september.',
  '• Mette Halling – marketingchef hos Lunar, din primære kundekontakt.',
  '• Signe – din ægtefælle. Alma (7) og Villum (4) er jeres børn.',
  '• Mikkel Holm – bedste ven, arbejder i Nordea, padel lørdag.',
  '',
  'Igangværende:',
  '• Q3-kampagnen for Lunar – tilbud skal sendes onsdag kl. 12.',
  '• Pleo-dialogen (Katrine Foss) – vigtigste nye lead til Q4.',
  '• Onboarding af Louise (praktikant).',
  '',
  'Løfter og aftaler:',
  '• Du lovede Mette det samlede Q3-tilbud senest onsdag.',
  '• Du skal ringe til Anders Brix om §4 i kontrakten.',
  '• Louise venter på din feedback på GreenMobility-casen.',
].join('\n');
